### ISSUE TITLE
Error Loading Agent: AttributeError and Invalid Argument when Selecting Agent in Timeline Editor

### ISSUE THREAD

**Issue by GertjanAntonisse** [Synestheticminds/UnderdogCowboy#14]
Description:
While using the Underdog Cowboy Toolset (TUI), an error occurs when attempting to load an existing agent through the Timeline Editor. Upon selecting an agent and confirming the selection, the application crashes with the following errors:

Steps to Reproduce:

- Open the Underdog Cowboy tool using the command line.
- Navigate to the Timeline Editor.
- Attempt to load an existing agent (e.g., UC_schrijver_linkedin_blog_posts).
- Confirm the selection.
- Observe the error message and crash.

![Image](https://github.com/user-attachments/assets/4aefa7ed-2208-4fe4-b9b8-26374274ca5e)

**Comment by rluijk** [comment]
@GertjanAntonisse Can you run this one also?
[plain_win_extended.py.zip](https://github.com/user-attachments/files/17918199/plain_win_extended.py.zip)

**Comment by rluijk** [comment]
fixed with os windows check
