### ISSUE TITLE
InvalidAgentNameError: Agent Name Validation Fails with Spaces in Name

### ISSUE THREAD

**Issue by GertjanAntonisse** [Synestheticminds/UnderdogCowboy#40]
When attempting to save a new agent with a name containing spaces (e.g., "AI Test Agent"), the application raises an InvalidAgentNameError. The error message indicates that only letters, numbers, and underscores are allowed, and the name must start with a letter or underscore.

This limitation is not communicated in the UI, leading to user confusion.

**Steps to Reproduce:**

1. Navigate to the New_Agent.
2. Type an agent name that includes spaces, e.g., AI Test Agent, in the "Agent Name" field.
3. Click the Create Agent button.

![Image](https://github.com/user-attachments/assets/496fed86-1bb9-4ba8-8762-2bb0c7cf157e)

**! Note:**
It is possible to save AI_test_agent (with underscores)
It is also not possible to save AI-test-agent

**Comment by rluijk** [comment]
yes, this is not optimal, but needed, because agent names are becoming useable in the python code.
Hence the strict rules. 

- normal error handling via a more friendly UX is indeed desired

**Comment by rluijk** [comment]
This shows a notification to the user, and the program will not throw an error
<img width="623" alt="Screenshot 2024-11-30 at 06 43 16" src="https://github.com/user-attachments/assets/769de5bf-02b5-4910-b06d-48d95b81f64b">

**Comment by rluijk** [comment]
#44
