### ISSUE TITLE
AttributeError: 'RichVisual' object has no attribute 'plain' when selecting an agent in the Timeline Editor

### ISSUE THREAD

**Issue by GertjanAntonisse** [Synestheticminds/UnderdogCowboy#7]
**Description**:
A bug was encountered in the Timeline Editor of the Underdog Cowboy tool. When selecting an agent, the application crashes and throws an AttributeError stating: 'RichVisual' object has no attribute 'plain'.

**Details**:
Error Location: timeline_editor_src.py, line 147
Error Message: AttributeError: 'RichVisual' object has no attribute 'plain'

Code Snippet: self.current_agent = event.agent_name.plain

It seems that event.agent_name is a RichVisual object, but it does not have a plain attribute.

**Steps to Reproduce:**
1. Start the Underdog Cowboy tool : uc-agent-flow
2. press load agent button
3. Select an agent from the list.
4. The application crashes and shows the error mentioned above.

**Logs**:
- Stack trace

C:\Users\gertj\AppData\Local\Programs\Python\Python312\Lib\site-packages\underdogcowboy\core\commandtools\agent_flow\screens\timeline_editor_src.py:147 in on_agent_selected

on(AgentSelected)
def on_agent_selected(self, event: AgentSelected):
    self.current_agent = event.agent_name.plain
AttributeError: 'RichVisual' object has no attribute 'plain'

**Environment**:
OS: [Specify the operating system, e.g., Windows 10]
Python Version: 3.12
Underdog Cowboy Version: [Specify the version, if known]

**Comment by rluijk** [comment]
@GertjanAntonisse I need the bug trace from the command line screen to investigate the issue

**Comment by rluijk** [comment]
Needs a walk through with the debugger,
- the "plain" is a known issue that pops up on occasion.
- The strange thing, is this is on a spot that has been used many times on mac, so needs investigation on windows after debug analysis with the debugger.

**Comment by rluijk** [comment]
@GertjanAntonisse 

This might be windows related issue.
I wrote a small test python file (see zip)
Can you run that (you might need to do a pip install of textual first)

`pip install textual`

[plain_win.py.zip](https://github.com/user-attachments/files/17913034/plain_win.py.zip)

Thanks.

This is the expected behaviour:
 ![Image](https://github.com/user-attachments/assets/c5711cda-a9f8-41bf-8db9-48c644db19b2)

**Comment by GertjanAntonisse** [comment]
After running the plain_win.py this message appears.

![Image](https://github.com/user-attachments/assets/72ce54a6-61dd-47ad-a717-6dc266c094d2)
